[package]

name = "portmidi"
version = "0.0.1"
authors = ["Philippe Delrieu <philippe.delrieu@free.fr>"]

[lib]
name = "portmidi"
crate-type = ["dylib", "rlib"]
path = "src/lib.rs"

[dependencies]
time = "*"
